# Site settings
title: JsPorrero
email: porrero.javier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog about Javascript and Front End Development.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.javierporrero.com" # the base hostname & protocol for your site
twitter_username: jsPorrero
github_username:  JPorry

timezone:       Europe/Spain
locale:         en_us
name:           "JSPorrero - A Blog about Javascript"
author:
  facebook:     jporry@gmail.com
  twitter:      jsPorrero
  google_plus:  porrero.javier@gmail.com

# Build settings
markdown: kramdown
